name: my_card
description: Cartão pessoal - Curso de Flutter e Dart.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - imagens/carlos.jpg

  fonts:
    - family: Pacifico
      fonts:
        - asset: fontes/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fontes/SourceSansPro-Regular.ttf